# Generated by Django 3.0.2 on 2020-03-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('age_group', models.BooleanField(default=False)),
                ('sneezing', models.BooleanField(default=False)),
                ('run_nose', models.BooleanField(default=False)),
                ('fatigue', models.BooleanField(default=False)),
                ('dry_cough', models.BooleanField(default=False)),
                ('fever', models.BooleanField(default=False)),
                ('sour_throat', models.BooleanField(default=False)),
                ('breathing', models.BooleanField(default=False)),
                ('cases_around', models.BooleanField(default=False)),
                ('sick_frequency', models.BooleanField(default=False)),
                ('pneumonia', models.BooleanField(default=False)),
            ],
        ),
    ]
