# Generated by Django 3.0.2 on 2020-03-07 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virusapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age_group',
        ),
    ]
